# name of the workflow
name: BOOKS

on:
  push:
    branches: [ main ]

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# Jobs in our workflow
jobs:
  integrate:
    #  machine/container
    runs-on: ubuntu-latest # docker image
    steps:
      # Step 1 - Checkout from repository
      - name: checkout-repo
        uses: actions/checkout@master

      # Step 2 - Setup node js environment
      - name: nodejs-env-setup
        uses: actions/setup-node@v1

      # Step 3 - Install mongodb
      - name: Start MongoDB v${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.2.0

      # Step 4 - Install npm dependencies from package.json
      - name: npm-dependencies-installation
        run: npm install
